# Copyright © SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

[package]
name = "launcher"
version = "0.2.5"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
build = "build.rs"
publish = false
license = "GPL-3.0-only OR LicenseRef-Slint-commercial"

[[bin]]
path = "main.rs"
name = "launcher"

[dependencies]
slint = { path = "../../api/rs/slint", default-features = false, features = ["compat-1-0"] }
mcu-board-support = { path = "../mcu-board-support", default-features = false }
printerdemo_mcu = { path = "../printerdemo_mcu", default-features = false, features = ["from_launcher"] }
memory = { path = "../memory", features = ["from_launcher"], default-features = false }
slide_puzzle = { path = "../slide_puzzle", features = ["from_launcher", "rand", "mcu-board-support"], default-features = false }

[build-dependencies]
slint-build = { path = "../../api/rs/build" }

